### DISCUSSION TITLE
Relative paths in `_targets.yaml`?

### DISCUSSION THREAD

**Discussion by wlangera** [ropensci-books/targets#90] [Help]
Hi

I am following [this tutorial](https://books.ropensci.org/targets/projects.html#multiple-projects) to have multiple target pipelines in a single R project `my_project`.
We work with several colleagues on this project with GitHub.
Some functionality is not working properly for me:

Consider the `_targets.yml`:

```
project_a:
  store: ./source/pipeline_a/store_a
  script: ./source/pipeline_a/store_a.R
project_b:
  store: ./source/pipeline_b/store_b
  script: ./source/pipeline_b/store_b.R
```

It has relative paths, such that colleagues can run these pipelines from the `my_project.Rproj`.

```r
library(targets)
Sys.setenv(TAR_PROJECT = "project_a")

tar_make()
```

However, as soon as `tar_make()` is run, the relative paths in the `_targets.yml` are change to absolute paths, e.g.:

```
project_a:
  store: C:/wlangera/R/git_repositories/my_project/source/pipeline_a/store_a
  script: C:/wlangera/R/git_repositories/my_project/source/pipeline_a/store_a.R
project_b:
  store: C:/wlangera/R/git_repositories/my_project/source/pipeline_b/store_b
  script: C:/wlangera/R/git_repositories/my_project/source/pipeline_b/store_b.R
```

This is not what we want, because when I push my changes to the shared repository, my colleagues won't be able to run 

```r
library(targets)
Sys.setenv(TAR_PROJECT = "project_a")

tar_make()
```

Since the relative paths are now absolute paths.

Am I missing something here? Is there an argument or option to avoid this?

**Comment by wlandau** [comment]
I tried to reproduce this on both Mac and Windows, and on my end, `targets` preserves the relative paths. You might try upgrading `targets` to the latest version (1.11.1).

**Comment by wlangera** [comment]
I am using v1.11.1. I even updated all my packages to the latest version, but this still hapens.

It also adds the following to the yaml:

```
use_crew: yes
```

Even when I run 

```r
library(targets)
Sys.setenv(TAR_PROJECT = "exploratory_analysis")

tar_make(use_crew = FALSE)
```

**Comment by wlandau** [comment]
Does this only happen in you full project, or does it happen in a minimal example? When I tried `_targets.yaml`:

```yaml
project_a:
  store: ./source/pipeline_a/store_a
  script: ./source/pipeline_a/script_a.R
project_b:
  store: ./source/pipeline_b/store_b
  script: ./source/pipeline_b/script_b.R
```

with a simple `./source/pipeline_a/script_a.R`:

```r
library(targets)
list(tar_target(a, TRUE))
```

Running `Sys.setenv(TAR_PROJECT = "project_a"); targets::tar_make()` with `targets` 1.11.1 did not change the contents of `_targets.yaml`.

If you try this simple example yourself, do you still see full paths inserted in `_targets.yaml`? Do you see the same issue even after you upgrade the `yaml` package to the latest version on CRAN?
